<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0</TargetFrameworks>
    <LangVersion>12</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PackageId>PowerSync.Common</PackageId>
    <Title>PowerSync.Common</Title>
    <Description>PowerSync.Common is a package that enables local-first and real-time reactive apps with embedded SQLite for .NET clients</Description>
    <Authors>PowerSync</Authors>
    <owners>powersync</owners>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/powersync-ja/powersync-dotnet</RepositoryUrl>
    <PackageProjectUrl>https://powersync.com</PackageProjectUrl>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <PackageReleaseNotes>https://github.com/powersync-ja/powersync-dotnet/PowerSync/PowerSync.Common/CHANGELOG.md</PackageReleaseNotes>
    <PackageTags>powersync local-first local-storage state-management offline sql db persistence sqlite sync </PackageTags>
    <PackageIcon>icon.png</PackageIcon>
    <NoWarn>NU5100</NoWarn>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <DefaultItemExcludes>$(DefaultItemExcludes);runtimes/**/*.*;</DefaultItemExcludes>
  </PropertyGroup>
  
  <ItemGroup>
    <InternalsVisibleTo Include="PowerSync.Common.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.66" />
    <PackageReference Include="Microsoft.Bcl.AsyncInterfaces" Version="9.0.1" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="9.0.1" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="6.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="6.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Nito.AsyncEx" Version="5.1.2" />
    <PackageReference Include="System.Threading.Channels" Version="8.0.0" />
    <PackageReference Include="ThrottleDebounce" Version="2.0.1" />
  </ItemGroup>

  <ItemGroup>
    <None Include="PowerSync.Common.targets" Pack="true" PackagePath="build\" />
    <None Include="PowerSync.Common.targets" Pack="true" PackagePath="buildTransitive\" />
  </ItemGroup>
  
  <!-- Check allows us to skip for all MAUI targets-->
  <!-- For monorepo-->
  <ItemGroup Condition="!$(TargetFramework.EndsWith('-android')) AND !$(TargetFramework.EndsWith('-ios')) AND !$(TargetFramework.EndsWith('-maccatalyst'))">
    <Content Include="runtimes\**\*.*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <!-- For releasing runtimes  -->
  <ItemGroup Condition="!$(TargetFramework.EndsWith('-android')) AND !$(TargetFramework.EndsWith('-ios')) AND !$(TargetFramework.EndsWith('-maccatalyst'))">
    <None Include="runtimes\**\*.*" Pack="true" PackagePath="runtimes\" />
  </ItemGroup>
  
  <ItemGroup>
    <None Include="..\..\icon.png" Pack="true" PackagePath="" />
    <None Include="README.md" Pack="true" PackagePath="" />
  </ItemGroup>
</Project>
